
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/avla_db?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    

server:
  servlet:
    context-path: /api
  port: 7078